name: "Release AUR"

on:
  release:
    types:
      - published

env:
  PKGNAME: uoj-data-converter

jobs:
  aur:
    name: "Update AUR"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ouuan'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Version
        id: get-version
        run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"

      - name: Update PKGBUILD
        run: |
          wget -c https://github.com/${{ github.repository }}/archive/${{ steps.get-version.outputs.version }}.tar.gz
          sha256sum=$(shasum -a 256 *.tar.gz | cut -d ' ' -f 1)
          sed -i "s/@VERSION@/${{ steps.get-version.outputs.version }}/g" aur/release/PKGBUILD aur/release/.SRCINFO
          sed -i "s/SKIP/${sha256sum}/" aur/release/PKGBUILD aur/release/.SRCINFO
          mv aur/release "$PKGNAME"

      - name: Check PKGBUILD
        uses: 2m/arch-pkgbuild-builder@master
        with:
          target: pkgbuild
          pkgname: ${{ env.PKGNAME }}

      - name: Check .SRCINFO
        uses: 2m/arch-pkgbuild-builder@master
        with:
          target: srcinfo
          pkgname: ${{ env.PKGNAME }}

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@master
        with:
          pkgname: ${{ env.PKGNAME }}
          pkgbuild: ${{ env.PKGNAME }}/PKGBUILD
          commit_username: Yufan You
          commit_email: ouuansteve@gmail.com
          commit_message: "Update from GitHub Actions: ${{ steps.get-version.outputs.version }}\n\nThe run ID: ${{ github.run_id }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
