name: "Release checksums"

on:
  release:
    types:
      - published

jobs:
  build:
    name: "Release checksums"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Download assets and generate checksums
        run: |
          mkdir -p downloads
          cd downloads
          dn() {
            wget -c "https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/uoj-data-converter-${{ steps.get_version.outputs.VERSION }}-$1"
          }
          dn linux-x86_64.AppImage
          dn windows-x64-setup.exe
          shasum -a 256 *.* > uoj-data-converter-${{ steps.get_version.outputs.VERSION }}-sha256-checksums.txt

      - name: Upload checksums
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: UOJ Data Converter ${{ steps.get_version.outputs.VERSION }}
          files: downloads/uoj-data-converter-${{ steps.get_version.outputs.VERSION }}-sha256-checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
